Rubnews API
astarub/campus_app pull request #12
Opened 2022-09-13 06:39 UTC by domai-tb

This PR adds the backend for requesting news of the university.

It includes:
- Requesting the actual news feed from `news.rub.de/newsfeed` and parse them into news entities
- Local caching of these entities with the package [hive](https://pub.dev/packages/hive)
- Unit testing of all important backend classes
- Connection of Feed UI with Rubnews API to show news inside the feed page

2022-09-19 09:20 UTC, C4s4r requested changes
Some minor code-style changes should be made before merging this PR.

Also we could think about adding **a short article description** below the image & title. If the data source doesn't support one, we could show a shrinked version of the actual content.

2022-09-19 09:20 UTC, C4s4r commented on lib/pages/rubnews/widgets/feed_item.dart
>  import 'package:animations/animations.dart';
Again here: In order to keep the order _dart, flutter, external packages, internal imports_ this should be moved down.
```suggestion
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:animations/animations.dart';
import 'package:cached_network_image/cached_network_image.dart';
```

2022-09-19 09:20 UTC, C4s4r commented on lib/utils/pages/feed_utils.dart
> +import 'package:flutter/widgets.dart';
Again here: In order to keep the order _dart, flutter, external packages, internal imports_ this should be moved down.
```suggestion
import 'package:flutter/widgets.dart';
import 'package:cached_network_image/cached_network_image.dart';

import 'package:campus_app/pages/rubnews/news_entity.dart';
import 'package:campus_app/pages/rubnews/widgets/feed_item.dart';
import 'package:campus_app/utils/pages/presentation_functions.dart';
```

2022-09-26 18:11 UTC, domai-tb commented on lib/pages/rubnews/rubnews_page.dart
> +          });
The performance drop was indicated by multiple calling of the `updateFeedAndFailures()`-function. I completly removed this by using the `RefreshIndicator`-widget.

2022-09-28 10:21 UTC, C4s4r approved these changes
Seems good to go now! 👍🏼

2022-10-02 14:22 UTC, C4s4r approved these changes
Looks good, ready to merge!

2022-10-02 14:33 UTC, merged