Integrate translation
astarub/campus_app pull request #171
Opened 2024-06-04 21:11 UTC by Noirox1

Integrated Translation to German and English, as well as baseline support for portuguese as interest in that was indicated in #167. This also makes progress on #155, I will update the wiki to match current progress in the near future.

2024-08-25 15:11 UTC, domai-tb requested changes
Hey @Noirox1, first of all, thanks for your work!  ^~^ 👍🏼 

I checked your changes and it looks good so far. The only thing, I'm a bit confused, did you edit any file in `lib/l10n` manually? 😅 Usually, you can generate them by using the [flutter_localizations](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization) package. This will generate these classes based on the `.arb`-files. Additionally translation can than be added really easily like @BizarrePenguin did in #167.  

Can you adjust the PR to use the `flutter_localizations` plugin and automatic generation? Thanks!

2024-08-31 14:27 UTC, Noirox1 commented
Hey @domai-tb, thanks for reviewing! Yes, I did indeed edit the files manually, since the automatic generation (like many features of flutter) did not work on my machine. Since the ARB files are simply a different formatting, I quickly copied over my translations and search/replaced the format differences, so they can now easily be edited in the future. Thanks for catching that and reminding me!

As a sidenote, my internship has already ended in July, so I might not find the time to make any more substantial changes than this, if you see any other work that needs to be done, feel free to contribute to this branch yourself!

2024-09-02 12:04 UTC, henry-herrmann commented
@domai-tb @Noirox1 I swiftly implemented the changes necessary for automatic generation of the `l10n` files.

2025-04-16 09:53 UTC, domai-tb commented
Will close this PR because it is already included within the branch `dynamic-translation` (that will be renamed to `feature/translation`).

2025-04-16 09:53 UTC, closed without merging